### ISSUE TITLE
Implement DFS for graph

### ISSUE THREAD

**Issue by LakshaySK106** [LakshaySK106/Algorithms#18]
Objective: Implement DFS traversal for a connected graph

**Comment by D-Anir** [comment]
Hey @LakshaySK106, I want to work on this, can you assign this to me?

**Comment by LakshaySK106** [comment]
Assigned!

**Comment by D-Anir** [comment]
@LakshaySK106 I have submitted my PR with the required changes. Please review them.
Thanks & Regards.
