### ISSUE TITLE
Huffman Coding

### ISSUE THREAD

**Issue by LakshaySK106** [LakshaySK106/Algorithms#37]
Objective: WAP to implement Huffman coding algorithm with O(N log N)time complexity and O(N) space complexity.

**Comment by Atharv-Nalwade** [comment]
I can implement this can I get assigned to this

**Comment by LakshaySK106** [comment]
You're assigned!

**Comment by Atharv-Nalwade** [comment]
Should I create a file in Greedy Algo. folder

**Comment by LakshaySK106** [comment]
Create your respective language folder if not exists

**Comment by Atharv-Nalwade** [comment]
Its cpp that I am implementing it and it do exits 
What I am doing is Code File and Add input/output , description, application and image in readme is that fine

**Comment by LakshaySK106** [comment]
Keep it simple and add just the code file

**Comment by Atharv-Nalwade** [comment]
OK

**Comment by Atharv-Nalwade** [comment]
Can check the pull req.

**Comment by Atharv-Nalwade** [comment]
Also one more thing your recursion folder can many more examples like Josephus Problem, Staircase Problem 
Can I create issue for that I would  like to add that problems also

**Comment by LakshaySK106** [comment]
Yes, you may if you want to :)
