### ISSUE TITLE
Prim’s Minimum Spanning Tree (MST) Algorithm

### ISSUE THREAD

**Issue by LakshaySK106** [LakshaySK106/Algorithms#5]
Objective: To implement Prim’s Minimum Spanning Tree (MST) Algorithm in your preferred language with the best possible Time and Space complexity.

Add it to the existing "Greedy Algo" directory otherwise create it.

**Comment by avinashdhakne** [comment]
Hi, could I contribute to this task?

**Comment by LakshaySK106** [comment]
Sure!

**Comment by Kraken-ops** [comment]
I want to contribute to this issue, please allot me to this issue.
