### ISSUE TITLE
Implementations of different Data Structures

### ISSUE THREAD

**Issue by LakshaySK106** [LakshaySK106/Algorithms#51]
Objective: Add implementations of different Data Structures(Stack, Queue, Circular Queue, Tree, Binary Tree, Binary Search Tee, B-Tree, B+ Tree, Fibonacci Heap, Priority Queue, Threaded Binary Tree, Trie, Graphs, Disjoint Set, etc.

*****AVOID DUPLICATES*****
CREATE NEW DIRECTORY "Data Structure" >> "Language Folder(Cpp, Python, Java, etc)" IF NOT EXISTS.

**Comment by Samarthasbhat** [comment]
i will solve stack in java please assign me this @LakshaySK106

**Comment by LakshaySK106** [comment]
Assigned @Samarthasbhat

**Comment by Samarthasbhat** [comment]
Thank You

**Comment by Samarthasbhat** [comment]
I solved the the issue please MR it

**Comment by SanjoySaha24** [comment]
I want to contribute. Please assign it @LakshaySK106  as my first contribution for hacktoberfest 2022.

**Comment by CoderKartik-1** [comment]
Hi there, I can code the Threaded Binary tree in an efficient manner. Please assign @LakshaySK106

**Comment by LakshaySK106** [comment]
Assigned @SanjoySaha24 @isheoran
