### ISSUE TITLE
Add Staircase Problem to Recursion

### ISSUE THREAD

**Issue by Atharv-Nalwade** [LakshaySK106/Algorithms#55]
Add the Staircase problem to recursion and state its implementation and problem statement

**Comment by Atharv-Nalwade** [comment]
Kindly assign this issue to me and add the labels

**Comment by LakshaySK106** [comment]
You don't need to create multiple issues to collaborate

**Comment by Atharv-Nalwade** [comment]
ok 
I would suggest keep the issue open so that someone else can contribute

**Comment by LakshaySK106** [comment]
What I meant was to keep the issues in a generalized format

**Comment by Atharv-Nalwade** [comment]
Okay
