### ISSUE TITLE
N Queen Problem

### ISSUE THREAD

**Issue by LakshaySK106** [LakshaySK106/Algorithms#7]
Objective: WAP to solve N Queen Problem in your preferred language with the best possible Time and Space complexity.

Add it to the existing "Backtracking" directory otherwise create it.

**Comment by roshan2152** [comment]
Hey @LakshaySK106 Please assign me this.

**Comment by aryanayush012** [comment]
I want To contribute .Please assign this to me. @LakshaySK106

**Comment by LakshaySK106** [comment]
Assigned @roshan2152 @aryanayush012
