### ISSUE TITLE
Selection Sort

### ISSUE THREAD

**Issue by AbhishekRana21** [LakshaySK106/Algorithms#72]
Objective: WAP for implementation of Selection Sort using C++

**Comment by AbhishekRana21** [comment]
Kindly add the labels and assign this issue to me.

**Comment by ShaluMishra13** [comment]
please assign this to me .I can do it very well

**Comment by LakshaySK106** [comment]
This has already been done. I'm gonna close this issue. Try resolving other mentioned issues or create a new one
