### ISSUE TITLE
palindrome linked list

### ISSUE THREAD

**Issue by Piyushjar** [LakshaySK106/Algorithms#94]

**Comment by anshulkumar2311** [comment]
Hii can you please assign this issue with me. As I'm already Solve this problem before.

**Comment by Bhavil-Ahuja** [comment]
Hey @LakshaySK106 , please assign this issue to me.

**Comment by LakshaySK106** [comment]
Assigned @Bhavil-Ahuja @anshulkumar2311 @Piyushjar

**Comment by Bhavil-Ahuja** [comment]
I have solved this issue in pull request #141
